name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
assignees:
  - chrisreddington
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report this issue! Please [check for existing bugs](https://github.com/github/gh-skyline/issues) before submitting. If you find one, feel free to add more information or give a 👍 to the original issue.
  - type: input
    id: gh-cli-version
    attributes:
      label: GitHub CLI Version
      description: What version of the GitHub CLI are you using?
      placeholder: 2.0.0
  - type: input
    id: gh-skyline-version
    attributes:
      label: gh-skyline Version
      description: What version of gh-skyline are you using?
      placeholder: 0.0.3
  - type: dropdown
    id: os
    attributes:
      label: What Operating System are you seeing the problem on?
      multiple: true
      options:
        - Linux
        - macOS
        - Windows
        - Other
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
